spring:
  cloud:
    gateway:
      routes:
        - id: create-user
          uri: https://gateway-poc-axh2wfbs7q-ew.a.run.app
          predicates:
            - Path=/users
            - Method=POST
          filters:
            - RewritePath=/users, /users/create

        - id: get-user
          uri: https://gateway-poc-axh2wfbs7q-ew.a.run.app
          predicates:
            - Method=GET
            - Path=/users/{id}

        - id: update-user
          uri: https://gateway-poc-axh2wfbs7q-ew.a.run.app
          predicates:
          - Path=/users/{id}
          - Method=POST
          filters:
            - RewritePath=/users/(?<id>.*), /users/${id}/update

        - id: delete-user
          uri: https://gateway-poc-axh2wfbs7q-ew.a.run.app
          predicates:
            - Path=/users/{id}
            - Method=POST
          filters:
            - RewritePath=/users/(?<id>.*), /users/${id}/delete

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
